### ISSUE TITLE
Python backend support

### ISSUE THREAD

**Issue by rzc331** [thanhsonng/chatgpt-voice#12]
Hi,

The front-end you designed looks awesome!

We have built a backend with python Flask, which includes some customized function calling codes with OpenAI API, all in python. However, it doesn't seem to work with the frontend. 

We've succeeded in locally running your typescript backend, but once switched to flask backend, even with same port, it always shows `Failed to get the response, please try again.` 

Would you mind briefly guide us how to hook this front-end to Flask? Even a way to traceback error would be much appreciated (right now we have no way to locate the bug)!

**Comment by sonngdev** [comment]
Hi,

There are two possibilities in your case. It is either:
- Your call to OpenAI is failing, or
- Your call to OpenAI succeeds, but the response can't be returned to the frontend.

I suggest you debug the backend first, try logging your request to OpenAI and the response to see if you have successfully connected to OpenAI using your API credentials. 

If that works, then the problem lies in the frontend-backend communication. Open the browser dev tool, see the Network tab to see what data the backend is returning, and continue logging in the backend to see why it is returning that data.

**Comment by rzc331** [comment]
Thanks for the prompt response!

Issue identified, it's related to CORS of flask. After using flask_cors the issue was resolved.

Many thanks!
